from core.views import (
    contact,
    delete_dependant,
    dependent_forms,
    dependent_forms_update,
    dependent_forms_view,
    get_client_ip,
    load_cities,
    load_stats,
    new_register,
)
from inventory.views import (
    add_stock,
    delete_stock,
    issue_item,
    re_order,
    receive_item,
    stock_detail,
    update_stock,
    view_history,
    view_stock,
)
from scrum_board.views import scrum_list, scrum_view

__all__ = [
    'new_register',
    'get_client_ip',
    'view_stock',
    'scrum_list',
    'scrum_view',
    'add_stock',
    'update_stock',
    'delete_stock',
    'stock_detail',
    'issue_item',
    'receive_item',
    're_order',
    'view_history',
    'dependent_forms',
    'dependent_forms_update',
    'dependent_forms_view',
    'delete_dependant',
    'load_stats',
    'load_cities',
    'contact',
]
